---

- name: Create '{{ secrets_dir }}' directory
  tags: ansible-vault, credentials, secrets
  file:
    path: '{{ secrets_dir }}'
    state: directory
    owner: '{{ ansible_env.USER }}' 
    group: '{{ ansible_env.USER }}' 
    mode: 0700

- name: Copy '{{ vaultpw_file }}' password file
  tags: ansible-vault, credentials, secrets
  copy:
    content: '{{ vaultpw }}'
    dest: '{{ secrets_dir }}/{{ vaultpw_file }}'
    owner: '{{ ansible_env.USER }}'
    group: '{{ ansible_env.USER }}'
    mode: 0600
